my/config/routes.rb
PhanMemKeToan::Application.routes.draw do

  get "users/index"
  root "main#index"
  resources :phieuchis do
    get "/thanhtoan", to: "phieuthus#thanhtoan"
  end
  
  resources :phieuthus
  resources :users
  delete "/signout", to: "sessions#destroy", as: "signout"
  get "/signin", to: "sessions#new"
  post "/signin", to: "sessions#create"
  post "/signout", to: "sessions#destroy"
  namespace :admin do
    root :to => "base#index"
    resources :users
  end
end

my/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title><%= @title || "QWERTY" %></title>

		<%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
		<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
		<%= csrf_meta_tags %>
		
		
		<link href="/menu_source/styles.css" rel="stylesheet" type="text/css">
		<script src="http://code.jquery.com/jquery-latest.min.js"></script>
		<script type='text/javascript' src='/menu_source/menu_jquery.js'></script>

		<div id='cssmenu'>
			<ul>
				<li class='active'>
					<span><%= link_to "Trang chủ", root_path %> </span></a>
				</li>
				<li class='has-sub'>
					<a href='#'><span>Kế toán</span></a>
					<ul>
						<li>
							<span><%= link_to "Phiếu thu", phieuthus_path %></span></a>
						</li>
						<li class='last'>
							<span><%= link_to "Phiếu chi", phieuchis_path %></span></a>
						</li>
					</ul>
				</li>
				<span> <% if !current_user.nil? %>
				<li>
					<span><%= link_to current_user.name , current_user %></span></a>
				</li>

						<li class='last'>
						<%= link_to "Đăng xuất", signout_path, method: :delete%>
						</li>
						<% else %>
						<li>
						<%= link_to "Đăng nhập", signin_path %>
						<% end %> </span></a>
				</li>
			</ul>
		</div>
		
	</head>
	<body>
		<% flash.each do |key, value| %>
		<div class='flash' id='
		<%= key %>
		'>
			<%= value %>
		</div>
		<% end %>
		<%= yield %>
	</body>

</html>