my/config/routes.rb
PhanMemKeToan::Application.routes.draw do

  get "users/index"
  root "main#index"
  resources :phieuchis do
    get "/thanhtoan", to: "phieuthus#thanhtoan"
  end
  
  resources :phieuthus
  resources :users
  delete "/signout", to: "sessions#destroy", as: "signout"
  get "/signin", to: "sessions#new"
  post "/signin", to: "sessions#create"
  post "/signout", to: "sessions#destroy"
  namespace :admin do
    root :to => "base#index"
    resources :users
  end
end

my/app/models/phieuchi.rb
# encoding: utf-8

class Phieuchi < ActiveRecord::Base
  validates :so_phieu ,presence: true, uniqueness: true
  validates :ho_va_ten_nguoi_nhan , presence: true
  validates :dia_chi , presence: true
  validates :ly_do_chi , presence: true
  validates :so_tien , numericality: { greater_than: 0 }
  
  
  
  
  def self.to_words(integer)
    ones_array = [' không ',' một ',' hai ',' ba ',' bốn ',' năm ',' sáu ',' bảy ',' tám ',' chín ']
    teens_array = [' mười ',' mười một ',' mười hai ',' mười ba ',' mười bốn ',' mười lăm ',' mười sáu ',' mười bảy ',' mười tám ',' mười chín ']
    tens_array = [' mươi ',' mười ',' hai mươi ',' ba mươi ',' bốn mươi ',' năm mươi ',' sáu mươi ',' bảy mươi ',' tám mươi ',' chín mươi ']

    result = ""

    #FOR MILLIONS
    writing = integer / 1_000_000_000
    left_over = integer % 1_000_000_000

    if writing > 0
      result << to_words(writing) << " tỉ "
    integer = left_over
    end

    #FOR MILLIONS
    writing = integer / 1_000_000
    left_over = integer % 1_000_000

    if writing > 0
      result << to_words(writing) << " triệu "
    integer = left_over
    end

    #FOR THOUSANDS
    writing = integer / 1000
    left_over = integer % 1000

    if writing > 0
      result << to_words(writing) << " ngàn "
    integer = left_over
    end

    #FOR HUNDREDS
    writing = integer / 100
    left_over = integer % 100

    if writing > 0
      result << to_words(writing) << " trăm "
    integer = left_over
    end

    #FOR TENS!!!
    writing = integer / 10
    left_over = integer % 10

    if writing > 0
      if writing == 1 && left_over > 0
      result << teens_array[left_over]
      left_over = 0
      else
      result << tens_array[writing]
      end
    end

    writing = left_over

    #FOR ONES!!!!
    if writing > 0
    result << ones_array[writing]
    end
    result
  end

end

my/app/controllers/phieuchis_controller.rb
class PhieuchisController < ApplicationController
  before_action :authorize_account!, only: [:new, :update, :destroy, :edit ]
  before_action :set_phieuchi, only: [:show, :edit, :update, :destroy ]
  before_action :require_signin!
  
  
  
  def index
    @phieuchis = Phieuchi.all
  end

  def new
    @phieuchi = Phieuchi.new
  end

  def create
    @phieuchi = Phieuchi.new(phieuchi_params)
    if @phieuchi.save
      flash[:notice] = "Phiếu chi của bạn đã được tạo"
      redirect_to @phieuchi
    else
      flash[:alert] = "Phiếu chi không thể tạo."

      render "new"
    end
  end

  def show
    @phieuchi = Phieuchi.find(params[:id])
    @phieuthus = Phieuthu.all
  end

  def edit
    @phieuchi = Phieuchi.find(params[:id])
  end

  def thanhtoan
    @phieuchi = Phieuchi.find(params[:phieuchi_id])
  rescue ActiveRecord::RecordNotFound
    flash[:alert] = "Phiếu chi bạn tìm không thấy"
    
    
    @phieuthu = Phieuthu.new(phieuthu_params)
    if @phieuthu.save
      flash[:notice] = "Phiếu thu của bạn đã được tạo"
      redirect_to @phieuthu
    else
      flash[:alert] = "Phiếu thu không thể tạo."

      render "thanhtoan"
    end
    redirect_to phieuchis_path
    end

  def update
    @phieuchi = Phieuchi.find(params[:id])
    if @phieuchi.update(phieuchi_params)
      flash[:notice] = "Phiếu chi của ban đã được cập nhật."
      redirect_to @phieuchi
    else
      flash[:alert] = "Cập nhật Phiếu chi thất bại."
      render "edit"
    end
  end

  def destroy
    @phieuchi = Phieuchi.find(params[:id])
    @phieuchi.destroy
    flash[:notice] = "Phiếu chi của bạn đã được xóa thành công"
    redirect_to phieuchis_path
  end

  private

  def phieuchi_params
    params.require(:phieuchi).permit(:so_phieu ,:ho_va_ten_nguoi_nhan, :dia_chi, :ly_do_chi , :so_tien )
  end



  private

  def set_phieuchi
    @phieuchi = Phieuchi.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    flash[:alert] = "Phiếu chi bạn tìm không thấy"
    redirect_to phieuchis_path
    end

end

my/app/helpers/phieuchis_helper.rb
module PhieuchisHelper
end

my/app/views/phieuchis/_form.html.erb
<center>
	﻿<%= form_for(@phieuchi) do |f| %>

	<% if @phieuchi.errors.any? %>
	<div id="error_explanation">
		<h2><%= pluralize(@phieuchi.errors.count, "error") %> </h2>

		<ul>
			<% @phieuchi.errors.full_messages.each do |msg| %>
			<li>
				<%= msg %>
			</li>
			<% end %>
		</ul>
	</div>
	<% end %>

	<table>

		<tr>
			<td align="right"> <%= f.label :so_phieu, "Số Phiếu" %> </td>
			<td align="left"> <%= f.text_field :so_phieu %> </td>
		</tr>

		<tr>
			<td align="right"> <%= f.label :ho_va_ten_nguoi_nhan, " Họ và Tên người nhận" %> </td>
			<td align="left"> <%= f.text_field :ho_va_ten_nguoi_nhan %> </td>
		</tr>

		<tr>
			<td align="right"> <%= f.label :dia_chi, "Địa chỉ " %> </td>
			<td align="left"> <%= f.text_field :dia_chi %> </td>
		</tr>

		<tr>
			<td align="right"> <%= f.label :ly_do_chi ,"Lý do chi " %> </td>
			<td align="left"> <%= f.text_field :ly_do_chi %> </td>
		</tr>

		<tr>
			<td align="right"> <%= f.label :so_tien, "Số tiền " %> </td>
			<td align="left"> <%= f.number_field :so_tien %> </td>
		</tr>

	</table>

	<% if @phieuchi.new_record? %>
	<%= f.submit " Tạo  phiếu  chi " %>
	<% else %>
	<%= f.submit "Cập nhật phiếu chi" %>
	<% end %>

	<% end %>
</center>

my/app/views/phieuchis/edit.html.erb
<center>﻿<h1>Sửa Phiếu Chi</h1></center>
<%= render "form" %>

my/app/views/phieuchis/index.html.erb
<% if current_user.isAccount! %>
<%= link_to "Tạo phiếu chi", new_phieuchi_path %>
<% end %>
<h2>Danh sách phiếu chi</h2>

<% tong_tien = 0 %>
<style type="text/css">
	.myTable {
		width: 1000px;
		background-color: #eee;
		border-collapse: collapse;
	}
	.myTable th {
		background-color: #000;
		color: white;
		width: 20%;
	}
	.myTable td, .myTable th {
		padding: 5px;
		border: 1px solid #000;
	}
</style>
<!-- End Styles -->
<table class="myTable">
	<tr>
		<th>Số phiếu</th>
		<th>Họ tên</th>
		<th>Lý do chi</th>
		<th>Số tiền</th>
		<th>Thao tác</th>
	</tr>
	<% @phieuchis.each do |phieuchi| %>

	<tr>
		<% tong_tien = tong_tien + phieuchi.so_tien %>
		<td align="center"><%= link_to phieuchi.so_phieu, phieuchi %></td>
		<td><%= phieuchi.ho_va_ten_nguoi_nhan %></td>
		<td align="right"><%= phieuchi.ly_do_chi %></td>
		<td align="right"><%= phieuchi.so_tien  %> đ</td>
		<td align="center"><%= link_to "Xóa",
		phieuchi_path(phieuchi),
		method: :delete,
		data: { confirm:
		"Xóa phiếu?"
		} %>
		<%= link_to "Sửa", edit_phieuchi_path(phieuchi) %> </td>
	</tr>
	<% end %>
</table>
<h4> Tổng số tiền đã chi: <%= tong_tien %> đồng</h4>

my/app/views/phieuchis/new.html.erb
<center>﻿<h1>Tạo phiếu chi</h1>
<%= render "form" %></center>