my/config/routes.rb
PhanMemKeToan::Application.routes.draw do

  get "users/index"
  root "main#index"
  resources :phieuchis do
    get "/thanhtoan", to: "phieuthus#thanhtoan"
  end
  
  resources :phieuthus
  resources :users
  delete "/signout", to: "sessions#destroy", as: "signout"
  get "/signin", to: "sessions#new"
  post "/signin", to: "sessions#create"
  post "/signout", to: "sessions#destroy"
  namespace :admin do
    root :to => "base#index"
    resources :users
  end
end

my/app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates :name ,presence: true, uniqueness: true
  validates :email, presence: true
  
  def to_s
    "#{name} (#{per})"
  end
  
  def isAdmin!
    return per == "admin"
  end
  
  def isAccount!
    return per == "account"
  end
  
  
  
end

my/app/controllers/users_controller.rb
# encoding: utf-8
class UsersController < ApplicationController

before_action :authorize_admin!, only: [:index, :destroy ]
before_action :set_user, only: [:show, :edit, :destroy, :update]
before_action :user_authentication, only: [:show, :edit ]


  def new
    @user = User.new
  end
  
  def update
    if @user.update(user_params)
      flash[:notice] = "Thông tin tài khoản đã được cập nhật."
      redirect_to @user
    else
      flash[:alert] = "Cập nhật thất bại."
      render "edit"
    end
  end
  
  
  
  
  def destroy
    if current_user == @user 
      flash[:notice] = "Không thể xóa người dùng hiện tại."
    else 
      @user.destroy
    end
     redirect_to (:back)
  end
  
  
  

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "Đăng kí thành công"
      redirect_to users_path
    else
      render :new
    end
  end
  
  def index
    @users = User.all
  end
  
  def show
  end
  
  def edit
  end

  private
  def user_authentication
    if @user != current_user and !current_user.isAdmin!
      redirect_to user_path(current_user)
    end
  end
  
  def set_user
    @user = User.find(params[:id])
  end
  
  def user_params
    params.require(:user).permit(:name,:password, :email, :password_confirmation, :per)
  end
end

my/app/helpers/users_helper.rb
module UsersHelper
end

my/app/views/users/_form.html.erb
<%= form_for @user do |f| %>
<% if @user.errors.any? %>
<div id="error_explanation">
	<h2><%= pluralize(@user.errors.count, "error") %>
	prohibited this user from being saved:</h2>
	<ul>
		<% @user.errors.full_messages.each do |msg| %>
		<li>
			<%= msg %>
		</li>
		<% end %>
	</ul>
</div>
<% end %>
<div align="center">
<table>
	<tr>
		<td align="right"> <%= f.label :name, "Tài khoản: " %> </td>
		<td align="left"> <%= f.text_field :name %> </td>
	</tr>

	<tr>
		<td align="right"> <%= f.label :email, "Địa chỉ email: " %> </td>
		<td align="left"> <%= f.text_field :email %> </td>
	</tr>

	<tr>
		<td align="right"> <%= f.label :password, "Mật khẩu: " %> </td>
		<td align="left"> <%= f.password_field :password %> </td>
	</tr>

	<tr>
		<td align="right"> <%= f.label :password_confirmation, "Oánh lại mật khẩu: " %> </td>
		<td align="left"> <%= f.password_field :password_confirmation %> </td>
	</tr>

	</p>
	<% if current_user.isAdmin! %>
	<tr>
		<td align="right"> <%= f.radio_button :per, "admin" %></td>
		<td align="left"> <%= f.label :per, "Quản trị viên" %> </td>
	</tr>
	
	<tr>
		<td align="right"> <%= f.radio_button :per, "account" %></td>
		<td align="left"> <%= f.label :per, "Kế toán" %> </td>
	</tr>

	<tr>
		<td align="right"> <%= f.radio_button :per, "normal" %></td>
		<td align="left"> <%= f.label :per, "Người dùng" %> </td>
	</tr>
	<% end %>


		
</table>
<% if @user.new_record? %>
		<%= f.submit "  Đ ă n g  k í  " %>
		<% else %>
		<%= f.submit "  C ậ p  n h ậ t  " %>
		<% end %>
		<% end %>
</div>


my/app/views/users/edit.html.erb
<center><h1>Sửa thông tin tài khoản</h1></center>
<%= render "form" %>

my/app/views/users/index.html.erb
<%= link_to "Người dùng mới", new_user_path %>
<ul id='users'>
	<% @users.each do |user| %>
	<li>
		<%= link_to user, [user] %> <%= link_to "Xóa",
		user_path(user),
		method: :delete,
		data: { confirm:
		"Xóa tài khoản: " + user.name
		} %>
	</li>
	<% end %>
</ul>

my/app/views/users/new.html.erb
<center><h1>Đăng kí</h1></center>
<%= render "form" %>

my/app/views/users/show.html.erb
<h1> Thông tin người dùng </h1>

Tài khoản: <b> <%= link_to @user.name, edit_user_path %></b>
<br>
Email: <b> <%= @user.email %></b>
<br>
<% if @user.isAdmin! %>
<%= link_to "Danh sách người dùng", users_path %>
<% end %>