my/config/routes.rb
PhanMemKeToan::Application.routes.draw do

  get "users/index"
  root "main#index"
  resources :phieuchis do
    get "/thanhtoan", to: "phieuthus#thanhtoan"
  end
  
  resources :phieuthus
  resources :users
  delete "/signout", to: "sessions#destroy", as: "signout"
  get "/signin", to: "sessions#new"
  post "/signin", to: "sessions#create"
  post "/signout", to: "sessions#destroy"
  namespace :admin do
    root :to => "base#index"
    resources :users
  end
end

my/app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end
end

my/app/helpers/main_helper.rb
module MainHelper
end

my/app/views/main/accept.html.erb
<p>
<%= link_to "Phiếu chi", phieuchis_path %>
</p>
<p>
<%= link_to "Phiếu thu", phieuthus_path %>
</p>

my/app/views/main/index.html.erb
<i><h1>Đơn giản  | 
	Dễ dùng</h1></i>





<!-- <nav>
	<ul>
		<li><%= link_to "Đăng ký", new_user_path %></li>
		<li><%= link_to "Đăng nhập", signin_path %></li>
	</ul>
</nav> -->
<!-- <p>
<%= link_to "Phiếu chi", phieuchis_path %>
</p>
<p>
<%= link_to "Phiếu thu", phieuthus_path %>
</p> -->

my/app/views/main/logged.html.erb


<% @status = "Đăng xuất" %>

<%= link_to "Quản lý tày khoản", nguoidungs_edit_path%>
<%= link_to "phieu chi", phieuchis_path%>
<%= link_to "phieu thu", phieuthus_path%>

my/app/views/main/logout.html.erb


<% @status = <%= link_to "Dang xuat",  %>

link_to Quan li tai khoan


<%= link_to "phieu chi", phieuchis_path%>
<%= link_to "phieu thu", phieuthus_path%>